{% set name = "swmm" %}
{% set version = "5.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyswmm/Stormwater-Management-Model/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9adc18d15f77d944e162b05c97b3222dea7297f0c67ecdf2a33cc5741c8d8340

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make  # [not win]
    - openmp  # [not aarch64 and not ppc64le]
    - libgomp  # [linux]
  host:
    - libgomp  # [linux]
    - openmp  # [not aarch64 and not ppc64le]
  run:
    - libgomp  # [linux]
    - openmp  # [not aarch64 and not ppc64le]
    - llvm-openmp  # [osx]
    - _openmp_mutex  # [linux]

about:
  home: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model
  license_family: MIT
  license: MIT
  license_file: LICENSE
  summary: Stormwater Management Model (aka SWMM).
  description: |
    SWMM is a dynamic hydrology-hydraulic water quality simulation model.
    It is used for single event or long-term (continuous) simulation of
    runoff quantity and quality from primarily urban areas. SWMM source
    code is written in the C Programming Language and released in the
    Public Domain.
  dev_url: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model

extra:
  recipe-maintainers:
    - lrntct
